USE [master]
GO

/****** Object:  Database [AccountRequest]    Script Date: 02/10/2011 10:47:03 ******/
CREATE DATABASE [AccountRequest] ON  PRIMARY 
( NAME = N'AccountRequest', FILENAME = N'D:\MSSQL\Database\AccountRequest.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AccountRequest_log', FILENAME = N'D:\MSSQL\Logs\AccountRequest_log.ldf' , SIZE = 3072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AccountRequest] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AccountRequest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AccountRequest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AccountRequest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AccountRequest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AccountRequest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AccountRequest] SET ARITHABORT OFF 
GO

ALTER DATABASE [AccountRequest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AccountRequest] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AccountRequest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AccountRequest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AccountRequest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AccountRequest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AccountRequest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AccountRequest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AccountRequest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AccountRequest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AccountRequest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AccountRequest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AccountRequest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AccountRequest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AccountRequest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AccountRequest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AccountRequest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AccountRequest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AccountRequest] SET  READ_WRITE 
GO

ALTER DATABASE [AccountRequest] SET RECOVERY FULL 
GO

ALTER DATABASE [AccountRequest] SET  MULTI_USER 
GO

ALTER DATABASE [AccountRequest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AccountRequest] SET DB_CHAINING OFF 
GO


